translator: ensure manpages_url exists
Sphinx v1.6.x series does not support the `manpages_url` feature, thus
the attribute may not be defined in the configuration. This can cause
the following exception to occur:

    AttributeError: No such config value: manpages_url

Adjust the initialization to check for the attribute first before
attempting to pull in a configured manpages URL value.

Signed-off-by: James Knight <james.d.knight@live.com>