intersphinx: support python 2.7
When generating an inventory file using a Python 2.7 interpreter, the
process can fail when unicode characters are being used:

    UnicodeDecodeError: 'ascii' codec can't [decode|encode] ...

Adding the `unicode_literals` import to prevent issues when decoding
data being processed by inventory building, and explicitly encode
`utf-8` to prevent encoding issues.

Signed-off-by: James Knight <james.d.knight@live.com>